const easterEggs = <String, ({String title, String message})>{
  'logo': (title: '女神被戳醒', message: '如此執著地戳本女神……若你練舞也有一半這麼勤快就好了'),
  'night': (title: '深夜練舞', message: 'Nyx 已經將夜幕覆上 Olympus，你竟還在凡間起舞？'),
  'hundredLoops': (
    title: '再一次就好',
    message: '一百次。凡人，你口中的『最後一次』，跟 Zeus 的承諾一樣不太可信。',
  ),
  'mirror': (title: '鏡像迷宮', message: '你再切下去，Moirai 都要以為你有六個命運了。'),
  'secret': (title: '百日秘密', message: '一百天。連 Moirai 都替你記下來了。這份紀錄，本女神准你帶走。'),
  'gaze': (title: '凝視女神', message: '欣賞本女神三分鐘了。本女神很好看，本女神知道。但你是不是該動了？'),
  'language': (title: '語言迷航', message: '中文也好，English 也罷。換哪種語言，本女神都會叫你去練舞。'),
  'frozen': (title: '時間停滯', message: '這個定格很有藝術感。只是……你本人也定格了嗎？'),
  'camera': (title: '鏡頭攻防戰', message: '十次了。你到底是在關鏡頭，還是在跟另一個自己談判？'),
  'speed': (title: '時間魔法師', message: '一下快，一下慢。你是想學舞，還是想把時間玩壞？'),
  'quarter': (title: '時間本體', message: '很好，我們現在可以看見時間本人。它走得比你還慢。'),
  'repeat': (title: '無限輪迴', message: '十次了。你是真的想循環，還是捨不得讓這一段結束？'),
  'unseal': (title: '解除封印', message: '封印解除。很好，現在讓本女神看看你剛才到底學會了什麼。'),
  'sculpt': (title: '十秒神蹟', message: '你不是在剪片，你是在雕刻。Michelangelo 看了都想拜你為師'),
  'duel': (title: '神之對決', message: '自己對上自己。很好，這場比賽你總算不會輸給別人了。'),
  'sides': (title: '左右為難', message: '換邊不會改變結果，但本女神理解你……就是很想再確認一次。'),
  'bones': (title: '骨感現實', message: '別緊張，每個舞者都有一點骨感。只是你今天特別明顯。'),
  'hades': (title: '冥界變身', message: '你切得這麼勤快，連 Hades 都以為你在報到。'),
  'monday': (title: '星期一倖存者', message: '星期一沒有打敗你。值得記上一筆。'),
  'friday': (title: '週五舞池', message: '今晚的舞池，不需要排隊。'),
  'newYear': (title: '跨年一舞', message: '新年已經到了，你還在跳。很好，本女神喜歡這種執著 。'),
  'leap': (title: '四年一天', message: '四年才多出來的一天，你拿來跳舞了。'),
  'april': (title: '四月愚人', message: '今日課程改為數學。第一題：五、六、七、八。答錯就重跳。'),
  'lastBeat': (title: '最後一拍', message: '今年最後一拍，本女神准你把它帶進明年。'),
  'exports': (title: '十份存檔', message: '十支。很好，你的黑歷史又多了十份。'),
  'notifications': (title: '通知之戰', message: '十次了。你到底是在設定通知，還是在跟本女神鬥智？'),
  'void': (title: '虛空之手', message: '十次了。你是在敲門，還是在召喚什麼東西？'),
  'return': (title: '歸來之人', message: '又回來了？本女神開始懷疑，你其實住在這裡。'),
};
